initial commit of RHD-971
adding wip

adding wip

added selenium server standlone for firefox

added selenium server standlone for firefox

added selenium server standlone for firefox

added more scenarios to cdk download flow

adding further work to cdk scenarios

adding further work to cdk download scenarios

Fixed broken scenario

Fixed broken scenarios (again)

removed puts that was added for debugging.

adding progress for downloads scenarios

adding wip

adding wip

rebasing.

adding wip

adding wip

adding wip

adding wip and fixed already initialized constant warning.

completed featured download scenarios

completed featured download scenarios

tidy up from previous rebase

fixed error 'save undefined method `save_screenshot' for #<Capybara::Poltergeist::Browser:0x007f79167b05e8> (NoMethodError)'

updated capybara and selenium dependencies

updated capybara and selenium dependencies

updated gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

fixed failing tests due to an issuw with phantomjs causing failures on CI
Fixed menu intems in base.html.slim

more horrible hacks for phantomjs issues.

removed @wip tag

adding wip

initial commit of DEVELOPER-2578

removed references to phantomjs, and hacks that were added due to phatom issues.

removed references to phantomjs

removed unused id's

updated capybara and selenium-webdriver gems

newline

adding browserstack wip

adding browserstack wip

added bash scripts for dicker test runs

fxed bash scripts

adding wip

adding wip

updated environment variable names

fixed unit tests.

added downloads helper to env

added remote drivers with download profiles

added some wait_for's that were causing failures on CI.

removed unused method

updated condition on method

newline

Merge branch 'DEVELOPER-2578' into RHD-971

adding wip

adding wip

adding wip

newline

updated Gemfile.lock

merging cdk download features into branch

ingnore CDK for now that there is an issue.

merging cdk download features into branch

adding download wip

fixed mechanize already initialized constant waning

global variables was set instead of instance variable.

updated gemfile to latest version of selenium-webdriver. Fixing failures running tests on latest v of firefox

fixed global variable that should have been instance

updated tests due to changes on login/register pages

initial commit of RHD-971

adding wip

adding wip

added selenium server standlone for firefox

added selenium server standlone for firefox

added selenium server standlone for firefox

added more scenarios to cdk download flow

adding further work to cdk scenarios

adding further work to cdk download scenarios

Fixed broken scenario

Fixed broken scenarios (again)

removed puts that was added for debugging.

adding progress for downloads scenarios

adding wip

adding wip

rebasing.

adding wip

adding wip

adding wip

adding wip and fixed already initialized constant warning.

completed featured download scenarios

completed featured download scenarios

tidy up from previous rebase

fixed error 'save undefined method `save_screenshot' for #<Capybara::Poltergeist::Browser:0x007f79167b05e8> (NoMethodError)'

updated capybara and selenium dependencies

updated capybara and selenium dependencies

updated gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

fixed failing tests due to an issuw with phantomjs causing failures on CI
Fixed menu intems in base.html.slim

more horrible hacks for phantomjs issues.

removed @wip tag

adding wip

initial commit of DEVELOPER-2578

removed references to phantomjs, and hacks that were added due to phatom issues.

removed references to phantomjs

removed unused id's

updated capybara and selenium-webdriver gems

newline

adding browserstack wip

adding browserstack wip

added bash scripts for dicker test runs

fxed bash scripts

adding wip

adding wip

updated environment variable names

fixed unit tests.

added downloads helper to env

added remote drivers with download profiles

added some wait_for's that were causing failures on CI.

removed unused method

updated condition on method

newline

Merge branch 'DEVELOPER-2578' into RHD-971

adding wip

adding wip

adding wip

newline

updated Gemfile.lock

merging cdk download features into branch

ingnore CDK for now that there is an issue.

merging cdk download features into branch

adding download wip

fixed mechanize already initialized constant waning

global variables was set instead of instance variable.

updated gemfile to latest version of selenium-webdriver. Fixing failures running tests on latest v of firefox

fixed global variable that should have been instance

updated cucumber.yml to ignore cdk tests for now

added temporary hack to redirect to staging pr env when downloading.