completed stubbed search tests
adding stubbed data arg to be true.

Updates to stubbed search tests.

Fixed broken unit tests

removed wip tag from search feature

updated jenkins test runner

Updates Permission

Permissions for Events and also a new role for product teams.

permission updates

rebasing, fixed unit tests.

wip

wip

wip for unit-tests

fixed undefined method 'default' error.

[DEVELOPER-3676] Fixed up unit tests for stubbed data invocations

wip

DEVELOPER-3676 - refactured search tests to have the ability to use stubbed data.

Ensure tests for Search, Resources and Stack Overflow can be ran using PhantomJS driver

removed puffing billy to see if that is what is causing failing unit tests.

removed puffing billy

reverted gemfile.lock

renamed docker browsers to chome, and firefox.

remote URL for selenium grid was missing.

wip

added drivers for phantomjs and chrome to speed tests up.

wip for DEVELOPER-3676

completed stubbed search tests.

completed search stubs

added missing stubs

speeded up stubbed tests. Removed hundreds of unnecessary yml files.

adding stubbed tests for So page (part one)

adding stubbed tests for So page (part two)

Merging DEVELOPER-3677 - stackOverflow stubbed tests, additional files added. Edited stubbed yml files to replace http:// with https://

adding stubbed tests for Resources page (part one)

adding stubbed tests for Resources page (complete).

DEVELOPER-3678 - updated stubbed yml files for resopurces to use https, rather than http.

fixed merge clash for browsers class.

uncommented out feature files.

removed acceptance test dependencies from top level Gemfile.

fixed broken unit tests.

fixed more broken unit tests, caused failures when rebasing.

Fixed broken search stubbed data.

removed Resources stubbed tests from this PR as there is issues with the Resources tests. Will fix and raise a seperate PR.

removed Resources stubbed tests from this PR as there is issues with the Resources tests. Will fix and raise a seperate PR.

Fixed 'Session [e7c59050-e2e1-46e7-87d7-2002f4a298da] was terminated due to TIMEOUT (org.openqa.grid.common.exception.GridException) (Selenium::WebDriver::Error::UnknownError)' error.

readded failing unit tests

Updated Gemfile and Gemfile.lock to match master to fix failing unit tests. Removed any acceptance test dependencies.

Fixed failing tests. Using a global variable for $browser was causing random failures to browser instance. Replaced $browser with @browser.

Fixed failing mobile test config.

Fixed failing mobile view tests.

Fixed flaky failing tests. Now using watir-ng to find angularjs elements. Hopefully fixed selenium grid timeouts by upping the grid browser timeout and grid timeout.

reduced number of browser sessions at one time to 5, therefore only loading 5 phantom and 5 chrome browsers at any given time.

Removed feature that was alreadyb removed ~1 month ago. Tidied up env.rb file.

removed previously deprecated scenario

adding progress for resources tests now resources page has been fixed.

Completed DEVELOPER-3678 - stub resources tests.

Completed DEVELOPER-3678 - fixed tests that were broken during last commit.

Removed ability to also use stubbed data for resources tests as they are broken and not part of this PR.

Addressed comments from Rob

Addressed comments from Rob