wip
updated available chromium devices json file.

wip

refactored browser.rb, removed some duplicated code

wip

WIP

wip

fixed failing test.

adding wip

removed ignore tags.

updated download manager rest calls for dl tests.

refactored technologies pages.

added ie11 to browsers, fixed tests for IE.

added edge browser testing

fixed broken tests, removed edge (too flaky) and re-added firefox to be tested on browserstack.

scaled browsers on CI to 3.

completed mobile tests

complete updates

additional changes

refactored cucumber rake file.

wip

wip

wip

wip

wip

completed ticket DEVELOPER-3485

renamed scenarios

removed redundant scenario

wip

wip

wip

wip

wip

completed refactor.

wip

added colour output.

fixed broken tests.

reduced chrome nodes back down to 2.

minor change

removed host to test for primary nav menu items.

Create download dir at runtime.

removed volume from docker-compose file for creating tmp download file. genral tidy up.

added job description to docker-compose file.

fix for unit tests.

fixing errors.

updated unit test for new env variables.

re-added download dir volume.

minor update.

upgraded docker to use selenium 3.0

removed mobile drupal tests.

reverting back to previous version of selenium. Latest version is too unreliable.

more refactoring.

added before/after hook for deleting downloal dir.

upped timeout for downloads.

rebased, fixed download checker.

rebased latest master

ignore kc tests for desktop profile

added mobile github status

reordered acceptance test status on Github.

fixed failing IE11 tests.

added missing gem dependency.

fixed broken social tests.

amended env and browsers to alight with master.

re-added retry to fix NET read timeout errors

updated to latest and greatest version of watir, and removed deprecated methods.

added new docker profile to use mobile drivers too

fixed broken test options

updated docker selenium to use latest version, and to match the watir-webdriver version.

refactored browsers and docker options files

attempting to fix Error forwarding the new session Empty pool of VM for setup Capabilities

reverting to previous version of docker-selenium

removed debug puts

fixed broken mobile tests

removed unnecessary return from rake file.

pushing wip for Rob to review.

fixed failing unit test

renamed test options to use ci rake task by default.

wip

fixed undefined method system error.

fixed NoMethodError: undefined method `initialize_report' for #<TestRunner:0x0055b7b5549eb8>

acceptance status should match the drupal PR docker-compose file.

[DEVELOPER-3534] Final changes to jenkins_test_runner.rb and added unit tests