fixed error 'save undefined method `save_screenshot' for #<Capybara::Poltergeist::Browser:0x007f79167b05e8> (NoMethodError)'
updated capybara and selenium dependencies

updated capybara and selenium dependencies

updated gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

updated gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

revert gemfile/gemfile.lock

fixed failing tests due to an issuw with phantomjs causing failures on CI
Fixed menu intems in base.html.slim

more horrible hacks for phantomjs issues.

removed @wip tag

adding wip

initial commit of DEVELOPER-2578

removed references to phantomjs, and hacks that were added due to phatom issues.

removed references to phantomjs

removed unused id's

updated capybara and selenium-webdriver gems

newline

adding browserstack wip

adding browserstack wip

added bash scripts for dicker test runs

fxed bash scripts

adding wip

adding wip

updated environment variable names

fixed unit tests.

added downloads helper to env

added remote drivers with download profiles

added some wait_for's that were causing failures on CI.

removed unused method

updated condition on method

newline

adding wip

adding wip

adding wip

adding final wip

tidy up, removed comment

newline

renamed driver

renamed driver

renamed driver

removed unused tests and added non javascript driver

added @javascript tags to scenarios that are required to be ran using javascript enabled browser.

renamed env variable for capybara driver

renamed env variable for capybara driver

adding final wip

readded logout tag

updated env variables for browserstack in docker-compose file.

removed unused code

adding readme file

reformatted readme

updated readme

updated readme

removed readme

--added final wip

--added final wip