Fixed issue introduced by previous merge into master. Should have only updated Blinkr!
DEVELOPER-4202 - Add Content for New Search Landing Page

DEVELOPER-4202 - Minor tweaks to code

DEVELOPER-4202 - Moved null results logic to results file

Removed unnecessary result logic from main search app

DEVELOPER-4202 - Moved logic to empty query and added events

DEVELOPER-4202 - Moved event fire to search query

DEVELOPER-4202 - Added unit testing for rhdp-search-empty-query

DEVELOPER-4202 - Removed bugged unit test for now.

DEVELOPER-4202 - Merged PR from Ian

DEVELOPER-4348 Added exclude from search option to promotion content type

DEVELOPER-4205 - UI & design updates for the on-site search page

DEVELOPER-4205 - UI & design updates for the on-site search page

Fixed the positioning of the relevance button on mobile

DEVELOPER-4205 - Updated the color and size for metadata

Updates styles on clear filters btn and clear search bar btw

Fixes position of relevance select on tablet/mobile

Updated build.js to include products

Updated svg location for 'X' icon

DEVELOPER-4205 - Updated the font size of clear filters

Fixes clear search btn

Updated /middleware referrer alert link

DEVELOPER-4109 Updated styles for adaptive placeholders

Dry run for Christian's webinar

Dry Run

Fix JSON

Latest DevNation Live Updates

Revert _jdf-stack

Added fixes for broken builds.

updated approved ignored links for prod Blinkr run.

Update drupal-namespace.js

Changing the product code for RHAMT

DEVELOPER-4200 Added "Scroll to top" button

DEVELOPER-4243 CSS for JavaOne 2017 page

DEVELOPER-4403 replaced text underneath the forum titles

DEVELOPER-4407 Added missing products to SO dropdown

DEVELOPER-4243 JavaOne 2017 - Fixes width of tables

DEVELOPER-4406: Update the add content dropdown

JIRA: https://issues.jboss.org/browse/DEVELOPER-4406

Added the missing content types to the menu.

DEVELOPER-4243 JavaOne 2017 Fixes width of tables

Scrub term before printing to page

Remove hard coded product names from tests. Too flaky. Ruby tests will be removed soon anyways.

Adding completed login/register tests.

Fix for dependancy hell. octokit was resolved to 4.7.0, which depends on
                         12:39:30     sawyer was resolved to 0.8.1, which depends on
                         12:39:30       addressable was resolved to 2.5.2, which depends on
                         12:39:30         public_suffix

Fix for dependancy hell #2 . octokit was resolved to 4.7.0, which depends on
                         12:39:30     sawyer was resolved to 0.8.1, which depends on
                         12:39:30       addressable was resolved to 2.5.2, which depends on
                         12:39:30         public_suffix

Fix for dependency hell #3 and cucumber tags was not configured correctly within the node jenkins runner.

Fix for dependency hell #4 Installing ruby 2.1 and specific version of octokit.

Fixed unit-tests

Moved Before hook as it is not supported by wdio-cucumber.

Tidy up and fix for flaky login test.

Fix for siteNav is not defined error in previous test run.

Fix for ERROR: Cannot find module '../../support/pages/home.page'

it works on my machine ....

Fix for browser 'undefined' and SOCKET errors.

Added a base image for tests, installs ruby bundler and node. The test images for js-unit-tests, e2e-tests and blc all then install any specific requirements for that test type.

Fixed broken build unit-tests

Merging Jasons changes

added missing WORKDIR to test base

Adding completed login/register tests.

Fix for dependancy hell. octokit was resolved to 4.7.0, which depends on
                         12:39:30     sawyer was resolved to 0.8.1, which depends on
                         12:39:30       addressable was resolved to 2.5.2, which depends on
                         12:39:30         public_suffix

Fix for dependancy hell #2 . octokit was resolved to 4.7.0, which depends on
                         12:39:30     sawyer was resolved to 0.8.1, which depends on
                         12:39:30       addressable was resolved to 2.5.2, which depends on
                         12:39:30         public_suffix

Fix for dependency hell #3 and cucumber tags was not configured correctly within the node jenkins runner.

Fix for dependency hell #4 Installing ruby 2.1 and specific version of octokit.

Fixed unit-tests

Moved Before hook as it is not supported by wdio-cucumber.

Tidy up and fix for flaky login test.

Fix for siteNav is not defined error in previous test run.

Fix for ERROR: Cannot find module '../../support/pages/home.page'

it works on my machine ....

Fix for browser 'undefined' and SOCKET errors.

Added a base image for tests, installs ruby bundler and node. The test images for js-unit-tests, e2e-tests and blc all then install any specific requirements for that test type.

Fixed broken build unit-tests

Merging Jasons changes

added missing WORKDIR to test base

Completed login/registration refactor

Updated jenkins runner to allow for kc test runs

wip

Completed login/registration test refactor.

Completed login/registration test refactor.

Added mobile config and ignored tests that require waiting for emails to be received.

Fixed unit-tests.

registration and download test scenarios

added tests for user profile

ignore report files

added latest changes to search tests

added better reporting to e2e test runs

Fixed unit-tests.

More improvements for keycloak tests.

More improvements for keycloak tests.

Added ignore tag to download tests.